apiVersion: v1
kind: Service
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4}}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zoonavigator.selectorLabels" . | nindent 4 }}
