apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "burrow.fullname" . }}
  labels:
    {{- include "burrow.labels" . | nindent 4 }}
data:
  burrow.toml: |
    [general]
    pidfile={{ .Values.burrow.config.general.pidfile | default "burrow.pid" | quote }}

    [logging]
    level={{ .Values.burrow.config.logging.level | default "info" | quote }}

    [httpserver.default]
    address={{ .Values.burrow.config.httpserver.default.address | default ":8000" | quote }}
    timeout={{ .Values.burrow.config.httpserver.default.timeout | default 300 }}

    [zookeeper]
    servers={{ include "burrow.servers" .Values.burrow.config.zookeeper.servers }}
    timeout={{ .Values.burrow.config.zookeeper.timout | default 6 }}
    root-path={{ .Values.burrow.config.zookeeper.rootPath | default "/burrow" | quote }}

    {{- $root := . }}

    {{ range $key, $value := .Values.burrow.config.clientProfile }}
    [client-profile.{{ $key }}]
    kafka-version={{ $value.kafkaVersion | default "0.8" | quote}}
    client-id="{{ $value.clientId | default "burrow-lagchecker" }}"
    {{ end }}

    {{ range $key, $value := .Values.burrow.config.cluster }}
    [cluster.{{ $value.clusterName | default $key }}]
    class-name={{ $value.className | default "kafka" | quote }}
    servers={{ include "burrow.servers" $value.servers }}
    topic-refresh={{ $value.topicRefresh | default 60 }}
    offset-refresh={{ $value.offsetRefresh | default 10 }}
    {{ end }}

    {{- range $key, $value := .Values.burrow.config.consumer }}
    [consumer.{{ $value.clusterName | default $key }}]
    class-name={{ $value.className | default "kafka" | quote }}
    cluster="{{ $value.clusterName | default $key }}"
    servers={{ include "burrow.servers" $value.servers }}
    group-blacklist={{ $value.groupBlacklist | default "^.*(console-consumer-|python-kafka-consumer-).*$" | quote }}
    group-whitelist={{ $value.groupWhitelist | default ".*" | quote }}
    start-latest={{ $value.startLatest | default false }}
    client-profile={{ with $value.clientProfile }}{{ . }}{{ end }}

    {{ end }}

    {{- range $key, $value := .Values.burrow.config.notifier }}
    [notifier.{{ $key }}]
    class-name={{ $value.className | default "http" | quote }}
    interval={{ $value.interval | default 60 }}
    threshold={{ $value.threshold | default 1 }}
    group-blacklist={{ $value.groupBlacklist | default "^.*(console-consumer-|python-kafka-consumer-).*$" | quote }}
    group-whitelist={{ $value.groupWhitelist | default "^.*$" | quote }}
    {{- if $value.extras }}
    extras={{ $value.extras }}
    {{- end }}
    send-close={{ $value.sendClose | default true }}
    url-open={{ $value.urlOpen | quote }}
    url-close={{ $value.urlClose | quote }}
    template-open={{  printf "%s/%s" $root.Values.burrow.templateDir $value.templateOpen | quote }}
    template-close={{  printf "%s/%s" $root.Values.burrow.templateDir $value.templateClose | quote }}
    {{- end }}
