apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: burrow
version: 0.1.1
icon: https://media.licdn.com/dms/image/C4D0BAQEj-Fx1qtIAKQ/company-logo_200_200/0?e=2159024400&v=beta&t=90Cva_S5-k44uPf_P11ZdHQ6WnUCjuSrTGQshbTvWVo
